// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmvnaawqhqyrxgaeeebm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhtdm5hYXdxaHF5cnhnYWVlZWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNDgzOTUsImV4cCI6MjA3MjkyNDM5NX0.d-oMiCqW0iq50qO-hWGmNJ4IWA90ZjFO1FZc3rlK8HQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});